/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	authorizationv1alpha1 "github.com/telekom/auth-operator/api/authorization/v1alpha1"
)

// ConstrainedImpersonationLimitsApplyConfiguration represents a declarative configuration of the ConstrainedImpersonationLimits type for use
// with apply.
//
// ConstrainedImpersonationLimits constrains Kubernetes constrained impersonation
// (KEP-5284) grants that RestrictedRoleDefinitions may declare.
//
// This complements RoleLimits.ForbiddenVerbs and
// RoleLimits.ForbiddenResourceVerbs, which can also match generated
// `impersonate:<mode>` / `impersonate-on:<mode>:<verb>` verbs directly. The
// dedicated block exists because the generated verbs are synthesised by the
// operator rather than authored by the tenant, so a verb-string denylist alone is
// easy to bypass by choosing a different mode.
type ConstrainedImpersonationLimitsApplyConfiguration struct {
	// Allowed enables constrained impersonation grants under this policy.
	// Defaults to false (deny by default).
	Allowed *bool `json:"allowed,omitempty"`
	// AllowedModes restricts which impersonation modes may be used. An empty list
	// with allowed=true permits every mode.
	AllowedModes []authorizationv1alpha1.ImpersonationMode `json:"allowedModes,omitempty"`
	// AllowedIdentityResources restricts which identity resources may be granted.
	// An empty list with allowed=true permits every identity resource.
	AllowedIdentityResources []authorizationv1alpha1.ImpersonationIdentityResource `json:"allowedIdentityResources,omitempty"`
	// IdentityNameLimits constrains the identity names (resourceNames) a tenant may
	// list in identity rules, using the same allow/deny prefix and suffix semantics
	// as subject limits.
	IdentityNameLimits *NameMatchLimitsApplyConfiguration `json:"identityNameLimits,omitempty"`
	// ForbiddenActionVerbs lists underlying request verbs that must not appear in
	// action rules. Entries are the bare verbs (e.g. "delete"), not the
	// `impersonate-on:<mode>:` encoded form.
	ForbiddenActionVerbs []string `json:"forbiddenActionVerbs,omitempty"`
	// ForbidLegacyFallback requires that the RestrictedRoleDefinition also excludes
	// the legacy bare "impersonate" verb via restrictedVerbs. This closes knob #8 of
	// the KEP integration surface: a pre-existing blanket `impersonate` grant wins by
	// fallback and silently defeats every constraint expressed here.
	ForbidLegacyFallback *bool `json:"forbidLegacyFallback,omitempty"`
	// MaxIdentityNames limits how many identity names a single grant may allowlist
	// across all identity rules. Nil means unlimited.
	MaxIdentityNames *int32 `json:"maxIdentityNames,omitempty"`
}

// ConstrainedImpersonationLimitsApplyConfiguration constructs a declarative configuration of the ConstrainedImpersonationLimits type for use with
// apply.
func ConstrainedImpersonationLimits() *ConstrainedImpersonationLimitsApplyConfiguration {
	return &ConstrainedImpersonationLimitsApplyConfiguration{}
}

// WithAllowed sets the Allowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allowed field is set to the value of the last call.
func (b *ConstrainedImpersonationLimitsApplyConfiguration) WithAllowed(value bool) *ConstrainedImpersonationLimitsApplyConfiguration {
	b.Allowed = &value
	return b
}

// WithAllowedModes adds the given value to the AllowedModes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedModes field.
func (b *ConstrainedImpersonationLimitsApplyConfiguration) WithAllowedModes(values ...authorizationv1alpha1.ImpersonationMode) *ConstrainedImpersonationLimitsApplyConfiguration {
	for i := range values {
		b.AllowedModes = append(b.AllowedModes, values[i])
	}
	return b
}

// WithAllowedIdentityResources adds the given value to the AllowedIdentityResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedIdentityResources field.
func (b *ConstrainedImpersonationLimitsApplyConfiguration) WithAllowedIdentityResources(values ...authorizationv1alpha1.ImpersonationIdentityResource) *ConstrainedImpersonationLimitsApplyConfiguration {
	for i := range values {
		b.AllowedIdentityResources = append(b.AllowedIdentityResources, values[i])
	}
	return b
}

// WithIdentityNameLimits sets the IdentityNameLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdentityNameLimits field is set to the value of the last call.
func (b *ConstrainedImpersonationLimitsApplyConfiguration) WithIdentityNameLimits(value *NameMatchLimitsApplyConfiguration) *ConstrainedImpersonationLimitsApplyConfiguration {
	b.IdentityNameLimits = value
	return b
}

// WithForbiddenActionVerbs adds the given value to the ForbiddenActionVerbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ForbiddenActionVerbs field.
func (b *ConstrainedImpersonationLimitsApplyConfiguration) WithForbiddenActionVerbs(values ...string) *ConstrainedImpersonationLimitsApplyConfiguration {
	for i := range values {
		b.ForbiddenActionVerbs = append(b.ForbiddenActionVerbs, values[i])
	}
	return b
}

// WithForbidLegacyFallback sets the ForbidLegacyFallback field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForbidLegacyFallback field is set to the value of the last call.
func (b *ConstrainedImpersonationLimitsApplyConfiguration) WithForbidLegacyFallback(value bool) *ConstrainedImpersonationLimitsApplyConfiguration {
	b.ForbidLegacyFallback = &value
	return b
}

// WithMaxIdentityNames sets the MaxIdentityNames field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxIdentityNames field is set to the value of the last call.
func (b *ConstrainedImpersonationLimitsApplyConfiguration) WithMaxIdentityNames(value int32) *ConstrainedImpersonationLimitsApplyConfiguration {
	b.MaxIdentityNames = &value
	return b
}
