/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	authorizationv1alpha1 "github.com/telekom/auth-operator/api/authorization/v1alpha1"
)

// ConstrainedImpersonationSpecApplyConfiguration represents a declarative configuration of the ConstrainedImpersonationSpec type for use
// with apply.
//
// ConstrainedImpersonationSpec is the first-class, typed expression of a
// Kubernetes constrained impersonation (KEP-5284) grant. The operator translates
// it into the exact RBAC PolicyRules the apiserver expects, so operators do not
// need to hand-write magic verb strings such as "impersonate-on:user-info:list".
//
// IMPORTANT — grants union, they do not correlate. The effective permission is
// the full cross product of every granted identity and every granted action. It
// is not possible to express "userA only for pods AND userB only for secrets" in
// a single grant; use two separate RoleDefinitions bound to different subjects.
type ConstrainedImpersonationSpecApplyConfiguration struct {
	// Mode selects the constrained impersonation mode the generated verbs target.
	Mode *authorizationv1alpha1.ImpersonationMode `json:"mode,omitempty"`
	// Identities are the identity allowlist rules. They generate cluster-scoped
	// PolicyRules in the authentication.k8s.io API group with the
	// `impersonate:<mode>` verb.
	Identities []ImpersonationIdentityRuleApplyConfiguration `json:"identities,omitempty"`
	// Actions are the action rules describing which requests may be made while
	// impersonating. They generate PolicyRules with `impersonate-on:<mode>:<verb>`
	// verbs against the target resources.
	//
	// An empty Actions list produces an identity-only grant, which by itself
	// authorizes nothing: the apiserver runs the action check FIRST and falls back
	// to legacy impersonation when it fails. Admission emits a warning in that case.
	Actions []ImpersonationActionRuleApplyConfiguration `json:"actions,omitempty"`
}

// ConstrainedImpersonationSpecApplyConfiguration constructs a declarative configuration of the ConstrainedImpersonationSpec type for use with
// apply.
func ConstrainedImpersonationSpec() *ConstrainedImpersonationSpecApplyConfiguration {
	return &ConstrainedImpersonationSpecApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *ConstrainedImpersonationSpecApplyConfiguration) WithMode(value authorizationv1alpha1.ImpersonationMode) *ConstrainedImpersonationSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithIdentities adds the given value to the Identities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Identities field.
func (b *ConstrainedImpersonationSpecApplyConfiguration) WithIdentities(values ...*ImpersonationIdentityRuleApplyConfiguration) *ConstrainedImpersonationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithIdentities")
		}
		b.Identities = append(b.Identities, *values[i])
	}
	return b
}

// WithActions adds the given value to the Actions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Actions field.
func (b *ConstrainedImpersonationSpecApplyConfiguration) WithActions(values ...*ImpersonationActionRuleApplyConfiguration) *ConstrainedImpersonationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithActions")
		}
		b.Actions = append(b.Actions, *values[i])
	}
	return b
}
