/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	authorizationv1alpha1 "github.com/telekom/auth-operator/api/authorization/v1alpha1"
)

// ImpersonationIdentityRuleApplyConfiguration represents a declarative configuration of the ImpersonationIdentityRule type for use
// with apply.
//
// ImpersonationIdentityRule grants permission to assume a specific class of
// identity while impersonating. Each rule becomes one RBAC PolicyRule in the
// authentication.k8s.io API group carrying the `impersonate:<mode>` verb.
//
// Identity rules for users, groups, uids, userextras and nodes are cluster-scoped
// and therefore require a ClusterRole target. Only serviceaccounts identity rules
// may be expressed from a namespaced Role.
type ImpersonationIdentityRuleApplyConfiguration struct {
	// Resource is the identity resource this rule grants against.
	Resource *authorizationv1alpha1.ImpersonationIdentityResource `json:"resource,omitempty"`
	// ExtraKey is the domain-prefixed extra key when Resource is "userextras".
	// It becomes the RBAC subresource, producing resources: ["userextras/<key>"].
	// Must be lowercase and a valid domain-prefixed path, matching the apiserver's
	// own validateExtra() checks. Required for userextras, forbidden otherwise.
	ExtraKey *string `json:"extraKey,omitempty"`
	// Names is the allowlist written to the PolicyRule's resourceNames. Values are
	// usernames, group names, UIDs, ServiceAccount names, node names or extra
	// values depending on Resource. "*" grants every name for this resource.
	//
	// Leave empty only for the associated-node mode, where the apiserver performs
	// the node association check itself and the rule intentionally carries no
	// resourceNames. For every other mode an empty Names list would grant
	// unrestricted impersonation and is rejected.
	Names []string `json:"names,omitempty"`
}

// ImpersonationIdentityRuleApplyConfiguration constructs a declarative configuration of the ImpersonationIdentityRule type for use with
// apply.
func ImpersonationIdentityRule() *ImpersonationIdentityRuleApplyConfiguration {
	return &ImpersonationIdentityRuleApplyConfiguration{}
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ImpersonationIdentityRuleApplyConfiguration) WithResource(value authorizationv1alpha1.ImpersonationIdentityResource) *ImpersonationIdentityRuleApplyConfiguration {
	b.Resource = &value
	return b
}

// WithExtraKey sets the ExtraKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtraKey field is set to the value of the last call.
func (b *ImpersonationIdentityRuleApplyConfiguration) WithExtraKey(value string) *ImpersonationIdentityRuleApplyConfiguration {
	b.ExtraKey = &value
	return b
}

// WithNames adds the given value to the Names field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Names field.
func (b *ImpersonationIdentityRuleApplyConfiguration) WithNames(values ...string) *ImpersonationIdentityRuleApplyConfiguration {
	for i := range values {
		b.Names = append(b.Names, values[i])
	}
	return b
}
