/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ImpersonationActionRuleApplyConfiguration represents a declarative configuration of the ImpersonationActionRule type for use
// with apply.
//
// ImpersonationActionRule grants permission to perform specific verbs on specific
// target resources *while* impersonating in the declared mode. Each rule becomes
// one RBAC PolicyRule carrying `impersonate-on:<mode>:<verb>` verbs against the
// target request's own API group, resource and namespace — there is no group
// override, so apiGroups/resources describe the impersonated request's target.
type ImpersonationActionRuleApplyConfiguration struct {
	// APIGroups are the target API groups. Use "" for the core group and "*" for
	// all groups.
	APIGroups []string `json:"apiGroups,omitempty"`
	// Resources are the target resources, optionally with a subresource
	// ("pods/log"). Use "*" for all resources.
	Resources []string `json:"resources,omitempty"`
	// ResourceNames optionally restricts the target resource names.
	ResourceNames []string `json:"resourceNames,omitempty"`
	// Verbs are the *underlying* request verbs, e.g. ["get", "list", "watch"].
	// The operator rewrites each entry to `impersonate-on:<mode>:<verb>`; do not
	// pre-encode the prefix here.
	//
	// The apiserver has no prefix wildcard for action verbs: "*" is accepted by
	// RBAC as a full wildcard, but "impersonate-on:<mode>:*" is not a thing.
	// Passing "*" therefore emits the bare "*" verb, which grants every verb
	// including plain (non-impersonated) access, so it is rejected by validation.
	Verbs []string `json:"verbs,omitempty"`
}

// ImpersonationActionRuleApplyConfiguration constructs a declarative configuration of the ImpersonationActionRule type for use with
// apply.
func ImpersonationActionRule() *ImpersonationActionRuleApplyConfiguration {
	return &ImpersonationActionRuleApplyConfiguration{}
}

// WithAPIGroups adds the given value to the APIGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the APIGroups field.
func (b *ImpersonationActionRuleApplyConfiguration) WithAPIGroups(values ...string) *ImpersonationActionRuleApplyConfiguration {
	for i := range values {
		b.APIGroups = append(b.APIGroups, values[i])
	}
	return b
}

// WithResources adds the given value to the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Resources field.
func (b *ImpersonationActionRuleApplyConfiguration) WithResources(values ...string) *ImpersonationActionRuleApplyConfiguration {
	for i := range values {
		b.Resources = append(b.Resources, values[i])
	}
	return b
}

// WithResourceNames adds the given value to the ResourceNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceNames field.
func (b *ImpersonationActionRuleApplyConfiguration) WithResourceNames(values ...string) *ImpersonationActionRuleApplyConfiguration {
	for i := range values {
		b.ResourceNames = append(b.ResourceNames, values[i])
	}
	return b
}

// WithVerbs adds the given value to the Verbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Verbs field.
func (b *ImpersonationActionRuleApplyConfiguration) WithVerbs(values ...string) *ImpersonationActionRuleApplyConfiguration {
	for i := range values {
		b.Verbs = append(b.Verbs, values[i])
	}
	return b
}
