/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PrincipalExtraMatchApplyConfiguration represents a declarative configuration of the PrincipalExtraMatch type for use
// with apply.
//
// PrincipalExtraMatch matches a single SubjectAccessReview spec.extra entry.
// The apiserver populates spec.extra from the authenticated requester's extra
// values, including impersonation-related keys such as
// authentication.kubernetes.io/node-name.
type PrincipalExtraMatchApplyConfiguration struct {
	// Key is the extra key to match, e.g. "authentication.kubernetes.io/node-name".
	Key *string `json:"key,omitempty"`
	// Values are the accepted values for Key. The principal matches when at least
	// one of the request's values for Key is listed here. Use ["*"] to require only
	// that the key is present with any non-empty value.
	Values []string `json:"values,omitempty"`
}

// PrincipalExtraMatchApplyConfiguration constructs a declarative configuration of the PrincipalExtraMatch type for use with
// apply.
func PrincipalExtraMatch() *PrincipalExtraMatchApplyConfiguration {
	return &PrincipalExtraMatchApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *PrincipalExtraMatchApplyConfiguration) WithKey(value string) *PrincipalExtraMatchApplyConfiguration {
	b.Key = &value
	return b
}

// WithValues adds the given value to the Values field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Values field.
func (b *PrincipalExtraMatchApplyConfiguration) WithValues(values ...string) *PrincipalExtraMatchApplyConfiguration {
	for i := range values {
		b.Values = append(b.Values, values[i])
	}
	return b
}
