/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PrincipalApplyConfiguration represents a declarative configuration of the Principal type for use
// with apply.
//
// Principal represents a requesting user or service account identity.
type PrincipalApplyConfiguration struct {
	// User is the requesting user in SubjectAccessReview request.
	User *string `json:"user,omitempty"`
	// Groups is the requesting user groups in SubjectAccessReview request.
	Groups []string `json:"groups,omitempty"`
	// Namespace scopes User to a Kubernetes ServiceAccount namespace. When set,
	// User may be either the short ServiceAccount name or the full
	// system:serviceaccount:<namespace>:<name> username.
	Namespace *string `json:"namespace,omitempty"`
	// UID matches SubjectAccessReview spec.uid, the UID of the authenticated
	// requester. Matching on UID pins a principal to one specific identity instance
	// even when usernames are reused, which matters for constrained impersonation
	// because the requester's UID is part of the impersonation authorization check.
	UID *string `json:"uid,omitempty"`
	// Extra matches SubjectAccessReview spec.extra entries. All listed matchers must
	// match (AND) for the principal to match. This makes attributes such as
	// authentication.kubernetes.io/node-name — the value the associated-node
	// impersonation mode is keyed on — usable in authorization decisions.
	Extra []PrincipalExtraMatchApplyConfiguration `json:"extra,omitempty"`
}

// PrincipalApplyConfiguration constructs a declarative configuration of the Principal type for use with
// apply.
func Principal() *PrincipalApplyConfiguration {
	return &PrincipalApplyConfiguration{}
}

// WithUser sets the User field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the User field is set to the value of the last call.
func (b *PrincipalApplyConfiguration) WithUser(value string) *PrincipalApplyConfiguration {
	b.User = &value
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *PrincipalApplyConfiguration) WithGroups(values ...string) *PrincipalApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *PrincipalApplyConfiguration) WithNamespace(value string) *PrincipalApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *PrincipalApplyConfiguration) WithUID(value string) *PrincipalApplyConfiguration {
	b.UID = &value
	return b
}

// WithExtra adds the given value to the Extra field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Extra field.
func (b *PrincipalApplyConfiguration) WithExtra(values ...*PrincipalExtraMatchApplyConfiguration) *PrincipalApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExtra")
		}
		b.Extra = append(b.Extra, *values[i])
	}
	return b
}
